version: '3'
services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    ports:
      - "4822:4822"

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ''    # not used with simple user-mapping
    depends_on:
      - guacd
    volumes:
      - ./user-mapping.xml:/etc/guacamole/user-mapping.xml:ro